import React, { useState, useRef, useEffect } from 'react';
import { 
  Gauge, 
  Play, 
  Square, 
  RotateCcw, 
  Activity, 
  ArrowDown, 
  ArrowUp, 
  Clock, 
  Server, 
  ShieldCheck, 
  AlertCircle, 
  Info,
  Download
} from 'lucide-react';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip } from 'recharts';
import { Badge } from '../components/Badge';
import { ExportModal } from '../components/ExportModal';

interface GraphPoint {
  time: number;
  speed: number;
  phase: 'download' | 'upload';
}

export const SpeedTestView: React.FC = () => {
  const [status, setStatus] = useState<
    'READY' | 'CONNECTING' | 'LATENCY_TEST' | 'DOWNLOAD_TEST' | 'UPLOAD_TEST' | 'FINALIZING' | 'COMPLETED' | 'ERROR'
  >('READY');

  const [downloadMbps, setDownloadMbps] = useState<number | null>(null);
  const [uploadMbps, setUploadMbps] = useState<number | null>(null);
  const [pingMs, setPingMs] = useState<number | null>(null);
  const [jitterMs, setJitterMs] = useState<number | null>(null);
  const [packetLossPercent, setPacketLossPercent] = useState<number | null>(null);
  const [currentInstantMbps, setCurrentInstantMbps] = useState<number>(0);
  const [graphData, setGraphData] = useState<GraphPoint[]>([]);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [testDuration, setTestDuration] = useState<number>(0);
  const [showExportModal, setShowExportModal] = useState(false);

  const abortControllerRef = useRef<AbortController | null>(null);
  const startTimeRef = useRef<number>(0);

  const runTest = async () => {
    // Reset state
    setStatus('CONNECTING');
    setDownloadMbps(null);
    setUploadMbps(null);
    setPingMs(null);
    setJitterMs(null);
    setPacketLossPercent(null);
    setCurrentInstantMbps(0);
    setGraphData([]);
    setErrorMessage(null);
    setTestDuration(0);

    abortControllerRef.current = new AbortController();
    startTimeRef.current = Date.now();

    try {
      // 1. LATENCY & JITTER PROBES
      setStatus('LATENCY_TEST');
      const pingSamples: number[] = [];
      for (let i = 0; i < 5; i++) {
        if (abortControllerRef.current?.signal.aborted) return;
        const pStart = performance.now();
        const pRes = await fetch('/api/network/speed-test/ping', {
          signal: abortControllerRef.current.signal,
          cache: 'no-store'
        });
        if (pRes.ok) {
          const pDuration = performance.now() - pStart;
          pingSamples.push(pDuration);
        }
        await new Promise(r => setTimeout(r, 100));
      }

      if (pingSamples.length > 0) {
        const avgPing = Math.round(pingSamples.reduce((a, b) => a + b, 0) / pingSamples.length);
        setPingMs(avgPing);

        let jitterTotal = 0;
        for (let i = 1; i < pingSamples.length; i++) {
          jitterTotal += Math.abs(pingSamples[i] - pingSamples[i - 1]);
        }
        const avgJitter = Math.round((jitterTotal / (pingSamples.length - 1)) * 10) / 10;
        setJitterMs(avgJitter);
        setPacketLossPercent(0);
      } else {
        setPacketLossPercent(100);
      }

      // 2. REAL DOWNLOAD THROUGHPUT TEST (Streams up to 10MB chunk)
      setStatus('DOWNLOAD_TEST');
      const downloadPayloadBytes = 12 * 1024 * 1024; // 12 MB real payload
      const dStart = performance.now();
      let dBytesReceived = 0;

      const dResponse = await fetch(`/api/network/speed-test/download?bytes=${downloadPayloadBytes}`, {
        signal: abortControllerRef.current.signal,
        cache: 'no-store'
      });

      if (!dResponse.ok || !dResponse.body) {
        throw new Error('Speed test download stream failed');
      }

      const reader = dResponse.body.getReader();
      const newPoints: GraphPoint[] = [];

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        dBytesReceived += value.length;

        const elapsedSec = Math.max((performance.now() - dStart) / 1000, 0.05);
        const instantMbps = ((dBytesReceived * 8) / (elapsedSec * 1000 * 1000));
        const roundedInstant = Math.round(instantMbps * 10) / 10;
        setCurrentInstantMbps(roundedInstant);

        newPoints.push({
          time: Math.round(elapsedSec * 10) / 10,
          speed: roundedInstant,
          phase: 'download'
        });
        setGraphData([...newPoints]);
      }

      const totalDownloadDurationSec = Math.max((performance.now() - dStart) / 1000, 0.01);
      const finalDownloadMbps = Math.round(((dBytesReceived * 8) / (totalDownloadDurationSec * 1000 * 1000)) * 10) / 10;
      setDownloadMbps(finalDownloadMbps);

      // 3. REAL UPLOAD THROUGHPUT TEST (Sends 5MB generated byte buffer)
      setStatus('UPLOAD_TEST');
      const uploadBytes = 5 * 1024 * 1024; // 5 MB payload
      const uploadBuffer = new Uint8Array(uploadBytes);
      for (let i = 0; i < uploadBytes; i += 1024) {
        uploadBuffer[i] = 42;
      }

      const uStart = performance.now();
      const uRes = await fetch('/api/network/speed-test/upload', {
        method: 'POST',
        headers: { 'Content-Type': 'application/octet-stream' },
        body: uploadBuffer,
        signal: abortControllerRef.current.signal
      });

      const uElapsedSec = Math.max((performance.now() - uStart) / 1000, 0.01);
      if (uRes.ok) {
        const uData = await uRes.json();
        const finalUploadMbps = uData.mbps || Math.round(((uploadBytes * 8) / (uElapsedSec * 1000 * 1000)) * 10) / 10;
        setUploadMbps(finalUploadMbps);
        setCurrentInstantMbps(finalUploadMbps);

        setGraphData(prev => [
          ...prev,
          {
            time: Math.round((totalDownloadDurationSec + uElapsedSec) * 10) / 10,
            speed: finalUploadMbps,
            phase: 'upload'
          }
        ]);
      }

      // 4. COMPLETION
      setStatus('COMPLETED');
      setTestDuration(Math.round((Date.now() - startTimeRef.current) / 1000));
    } catch (err: any) {
      if (err.name === 'AbortError') {
        setStatus('READY');
      } else {
        setStatus('ERROR');
        setErrorMessage(err.message || 'Speed test encountered a network transfer error.');
      }
    }
  };

  const stopTest = () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
    }
    setStatus('READY');
  };

  return (
    <div className="min-h-screen pt-24 pb-16 px-4 sm:px-6 max-w-7xl mx-auto space-y-8">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-white/10">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono text-purple-400 font-bold uppercase tracking-widest mb-1">
            <span>// NETWORK DIAGNOSTICS</span>
            <span>&bull;</span>
            <Badge type="REAL TEST" size="sm" />
          </div>
          <h1 className="font-heading font-black text-3xl sm:text-4xl text-white tracking-tight">
            REAL NETWORK SPEED TEST
          </h1>
          <p className="text-xs sm:text-sm text-slate-400 font-sans mt-1">
            Byte-level transfer measurement via dedicated high-bandwidth streaming endpoints. Zero simulated numbers.
          </p>
        </div>

        <div className="flex items-center gap-3">
          {status === 'CONNECTING' || status === 'LATENCY_TEST' || status === 'DOWNLOAD_TEST' || status === 'UPLOAD_TEST' ? (
            <button
              onClick={stopTest}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-rose-600/20 hover:bg-rose-600/30 text-rose-300 border border-rose-500/40 text-xs font-mono font-bold tracking-wider uppercase transition-colors"
            >
              <Square className="w-4 h-4 fill-current" />
              STOP TEST
            </button>
          ) : (
            <button
              onClick={runTest}
              className="flex items-center gap-2 px-6 py-2.5 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white text-xs font-mono font-bold tracking-wider uppercase shadow-lg shadow-purple-950 border border-purple-400/40 hover:scale-[1.02] transition-all"
            >
              <Play className="w-4 h-4 fill-current" />
              {status === 'COMPLETED' ? 'RETEST SPEED' : 'START TEST'}
            </button>
          )}

          {status === 'COMPLETED' && (
            <button
              onClick={() => setShowExportModal(true)}
              className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-slate-200 border border-white/10 text-xs font-mono font-medium transition-colors"
            >
              <Download className="w-4 h-4 text-purple-400" />
              Export
            </button>
          )}
        </div>
      </div>

      {/* Main Metric Cards Grid */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
        {/* DOWNLOAD */}
        <div className="rounded-2xl glass-panel p-5 border border-white/10 flex flex-col justify-between">
          <div className="flex items-center justify-between text-slate-400 text-xs font-mono uppercase tracking-wider mb-2">
            <span className="flex items-center gap-1.5 text-cyan-400">
              <ArrowDown className="w-4 h-4" />
              DOWNLOAD
            </span>
            <span className="text-[10px] text-slate-500">Mbps</span>
          </div>
          <div className="font-heading font-black text-3xl sm:text-4xl text-white tracking-tight">
            {status === 'DOWNLOAD_TEST' ? (
              <span className="text-cyan-400 animate-pulse">{currentInstantMbps.toFixed(1)}</span>
            ) : downloadMbps !== null ? (
              downloadMbps.toFixed(1)
            ) : (
              '--'
            )}
          </div>
          <div className="text-[11px] font-mono text-slate-500 mt-2">
            {downloadMbps ? 'Measured via 12MB Stream' : 'Not tested'}
          </div>
        </div>

        {/* UPLOAD */}
        <div className="rounded-2xl glass-panel p-5 border border-white/10 flex flex-col justify-between">
          <div className="flex items-center justify-between text-slate-400 text-xs font-mono uppercase tracking-wider mb-2">
            <span className="flex items-center gap-1.5 text-purple-400">
              <ArrowUp className="w-4 h-4" />
              UPLOAD
            </span>
            <span className="text-[10px] text-slate-500">Mbps</span>
          </div>
          <div className="font-heading font-black text-3xl sm:text-4xl text-white tracking-tight">
            {status === 'UPLOAD_TEST' ? (
              <span className="text-purple-400 animate-pulse">{currentInstantMbps.toFixed(1)}</span>
            ) : uploadMbps !== null ? (
              uploadMbps.toFixed(1)
            ) : (
              '--'
            )}
          </div>
          <div className="text-[11px] font-mono text-slate-500 mt-2">
            {uploadMbps ? 'Measured via 5MB Post' : 'Not tested'}
          </div>
        </div>

        {/* PING */}
        <div className="rounded-2xl glass-panel p-5 border border-white/10 flex flex-col justify-between">
          <div className="flex items-center justify-between text-slate-400 text-xs font-mono uppercase tracking-wider mb-2">
            <span className="flex items-center gap-1.5 text-emerald-400">
              <Clock className="w-4 h-4" />
              PING
            </span>
            <span className="text-[10px] text-slate-500">ms</span>
          </div>
          <div className="font-heading font-black text-3xl sm:text-4xl text-white tracking-tight">
            {pingMs !== null ? pingMs : '--'}
          </div>
          <div className="text-[11px] font-mono text-slate-500 mt-2">
            Round-trip socket latency
          </div>
        </div>

        {/* JITTER */}
        <div className="rounded-2xl glass-panel p-5 border border-white/10 flex flex-col justify-between">
          <div className="flex items-center justify-between text-slate-400 text-xs font-mono uppercase tracking-wider mb-2">
            <span className="flex items-center gap-1.5 text-amber-400">
              <Activity className="w-4 h-4" />
              JITTER
            </span>
            <span className="text-[10px] text-slate-500">ms</span>
          </div>
          <div className="font-heading font-black text-3xl sm:text-4xl text-white tracking-tight">
            {jitterMs !== null ? jitterMs : '--'}
          </div>
          <div className="text-[11px] font-mono text-slate-500 mt-2">
            Delay variation
          </div>
        </div>

        {/* PACKET LOSS */}
        <div className="rounded-2xl glass-panel p-5 border border-white/10 flex flex-col justify-between">
          <div className="flex items-center justify-between text-slate-400 text-xs font-mono uppercase tracking-wider mb-2">
            <span className="flex items-center gap-1.5 text-rose-400">
              <ShieldCheck className="w-4 h-4" />
              LOSS
            </span>
            <span className="text-[10px] text-slate-500">%</span>
          </div>
          <div className="font-heading font-black text-3xl sm:text-4xl text-white tracking-tight">
            {packetLossPercent !== null ? `${packetLossPercent}%` : '--'}
          </div>
          <div className="text-[11px] font-mono text-slate-500 mt-2">
            Unacknowledged packets
          </div>
        </div>
      </div>

      {/* Real-Time Throughput Graph */}
      <div className="rounded-2xl glass-panel p-6 border border-white/10 space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-3 border-b border-white/10">
          <div className="flex items-center gap-2">
            <Activity className="w-4 h-4 text-purple-400" />
            <h3 className="font-heading font-bold text-sm text-white tracking-wider uppercase">
              THROUGHPUT TELEMETRY GRAPH
            </h3>
          </div>
          <div className="flex items-center gap-4 text-xs font-mono text-slate-400">
            <span className="flex items-center gap-1.5">
              <span className="w-2.5 h-2.5 rounded-full bg-cyan-400" />
              Download Stream
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-2.5 h-2.5 rounded-full bg-purple-400" />
              Upload Stream
            </span>
          </div>
        </div>

        <div className="h-64 w-full">
          {graphData.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-center text-slate-500 font-mono text-xs space-y-2 border border-dashed border-white/10 rounded-xl">
              <Gauge className="w-8 h-8 text-slate-600" />
              <span>Throughput graph will render here during active data transfer.</span>
            </div>
          ) : (
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={graphData}>
                <defs>
                  <linearGradient id="speedGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#38bdf8" stopOpacity={0.4} />
                    <stop offset="95%" stopColor="#818cf8" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <XAxis dataKey="time" stroke="#64748b" tick={{ fontSize: 10, fill: '#64748b' }} unit="s" />
                <YAxis stroke="#64748b" tick={{ fontSize: 10, fill: '#64748b' }} unit=" Mbps" />
                <Tooltip
                  contentStyle={{ backgroundColor: '#0e0e17', borderColor: 'rgba(255,255,255,0.15)', borderRadius: '8px', fontSize: '12px' }}
                  formatter={(value: any) => [`${value} Mbps`, 'Transfer Speed']}
                  labelFormatter={(label) => `Time: ${label}s`}
                />
                <Area type="monotone" dataKey="speed" stroke="#38bdf8" strokeWidth={2} fillOpacity={1} fill="url(#speedGrad)" />
              </AreaChart>
            </ResponsiveContainer>
          )}
        </div>
      </div>

      {/* Test Server Information & Methodology */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Server Info */}
        <div className="rounded-2xl glass-panel p-6 border border-white/10 space-y-3">
          <div className="flex items-center gap-2 text-xs font-mono text-slate-300 font-bold uppercase tracking-wider">
            <Server className="w-4 h-4 text-purple-400" />
            DIAGNOSTIC TEST SERVER DETAILS
          </div>
          <div className="grid grid-cols-2 gap-3 text-xs font-mono pt-2">
            <div className="p-3 rounded-lg bg-[#090912] border border-white/5">
              <span className="text-slate-500 block text-[10px]">SERVER ENGINE</span>
              <span className="text-white font-semibold">Tendry Telecom Node Core</span>
            </div>
            <div className="p-3 rounded-lg bg-[#090912] border border-white/5">
              <span className="text-slate-500 block text-[10px]">TRANSFER PROTOCOL</span>
              <span className="text-white font-semibold">HTTP/2 Binary Stream</span>
            </div>
            <div className="p-3 rounded-lg bg-[#090912] border border-white/5">
              <span className="text-slate-500 block text-[10px]">DOWNLOAD ENDPOINT</span>
              <span className="text-white font-semibold">/api/network/speed-test/download</span>
            </div>
            <div className="p-3 rounded-lg bg-[#090912] border border-white/5">
              <span className="text-slate-500 block text-[10px]">UPLOAD ENDPOINT</span>
              <span className="text-white font-semibold">/api/network/speed-test/upload</span>
            </div>
          </div>
        </div>

        {/* Engineering Notice */}
        <div className="rounded-2xl glass-panel p-6 border border-white/10 space-y-3">
          <div className="flex items-center gap-2 text-xs font-mono text-slate-300 font-bold uppercase tracking-wider">
            <Info className="w-4 h-4 text-cyan-400" />
            TECHNICAL INTERPRETATION
          </div>
          <p className="text-xs text-slate-400 font-sans leading-relaxed">
            Speed results depend on the test server route, container ingress, client device capabilities, and current network congestion. Throughput is computed mathematically using transferred payload bytes divided by high-precision performance elapsed time:
          </p>
          <div className="p-2.5 rounded-lg bg-[#050508] border border-white/10 font-mono text-xs text-purple-300">
            Throughput (Mbps) = (Bytes Transferred &times; 8) / (Elapsed Seconds &times; 1,000,000)
          </div>
        </div>
      </div>

      {/* Export Modal */}
      {showExportModal && (
        <ExportModal
          isOpen={showExportModal}
          onClose={() => setShowExportModal(false)}
          title="Network Speed Test Results"
          toolName="Network Speed Test"
          inputs={{
            server: 'Tendry Telecom Node Core',
            protocol: 'HTTP Binary Stream',
            downloadPayload: '12 Megabytes',
            uploadPayload: '5 Megabytes'
          }}
          results={{
            downloadThroughput: `${downloadMbps} Mbps`,
            uploadThroughput: `${uploadMbps} Mbps`,
            pingLatency: `${pingMs} ms`,
            jitter: `${jitterMs} ms`,
            packetLoss: `${packetLossPercent}%`,
            duration: `${testDuration} seconds`
          }}
          formula="Throughput (Mbps) = (Bytes Transferred * 8) / (Elapsed Time * 10^6)"
        />
      )}
    </div>
  );
};
